# Generated by Django 4.1.2 on 2022-10-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('parcela', models.IntegerField()),
                ('qtd_parcela', models.IntegerField()),
                ('valor_parcela', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
    ]
